#!/bin/bash
# ============================================================================
# Plate-level cell processing — bundles all cells of one plate into one job.
#
# Why: original condor_proc.sh processed 1 cell per job → 18,468 jobs/brick,
# each xrdcp'ing the same 17 GB raw.root (5.5 TB transferred per plate).
# This script processes all ~324 cells of a plate in ONE job:
#   - xrdcp raw.root ONCE (17 GB instead of 5.5 TB per plate)
#   - run cells in parallel via xargs -P (default: $(nproc))
#   - 57 jobs per brick instead of 18,468 (324× fewer)
#
# Args from .sub: $(ClusterID) $(RUN) $(BRICK) $(BRICKFOLDER)
#                 $(PLATENUMBER) $(PLATEFOLDER) $(EXP_DIR)
# ============================================================================

set +u
export EOSSHIP=root://eospublic.cern.ch/

CLUSTER=$1
RUN=$2
BRICKID=$3
BRICKFOLDER=$4
PLATENUMBER=$5
PLATEFOLDER=$6
EXP_PRE=$7

# Subfolder within RUN$RUN that holds this brick (RUN1-specific naming)
RUNSUBDIR=RUN1_W4_B4_SG

# Cell list generated by gen_plate_cells.sh — one file per plate
CELLS_FILE=$(printf "cells_p%03d.dat" $PLATENUMBER)
if [ ! -f "$CELLS_FILE" ]; then
  echo "ERROR: cell list $CELLS_FILE not found — did you run gen_plate_cells.sh?"
  exit 1
fi

echo "=========================================================================="
echo "Plate-level cell processing"
echo "  Plate: $PLATENUMBER  Brick: $BRICKID  Run: $RUN  Started: $(date)"
echo "=========================================================================="

# ----- Environment ---------------------------------------------------------
echo "Set up SND environment"
SNDBUILD_DIR=/afs/cern.ch/user/s/snd2cern/public/SNDBUILD/sw
source /cvmfs/sndlhc.cern.ch/SNDLHC-2025/Oct7/setUp.sh
eval `alienv load -w $SNDBUILD_DIR --no-refresh sndsw/latest`
echo "Loading FEDRA"
source /afs/cern.ch/user/s/snd2cern/public/fedra/setup_new.sh

export LD_PRELOAD=/cvmfs/sndlhc.cern.ch/SNDLHC-2025/Oct7/sw/slc9_x86-64/XRootD/latest/lib/libXrdPosixPreload.so
export XROOTD_VMP=eospublic.cern.ch:/eos=/eos

# ----- O2 libraries (Mosaic + Alignment) -----------------------------------
OMP_EOS_SRC=root://eospublic.cern.ch//eos/experiment/sndlhc/users/vacharit/fedra-perf/profiling_test/build_omp/lib
O2_LIB_DIR=/tmp/fedra_o2_lib_$$
mkdir -p $O2_LIB_DIR
xrdcp -f $OMP_EOS_SRC/libMosaic.so    $O2_LIB_DIR/
xrdcp -f $OMP_EOS_SRC/libAlignment.so $O2_LIB_DIR/
export LD_LIBRARY_PATH="$O2_LIB_DIR:${LD_LIBRARY_PATH}"
echo "O2 libs loaded: $(ls $O2_LIB_DIR/)"

# ----- Detect resources -----------------------------------------------------
NCPUS=$(nproc)
if [ -f "$_CONDOR_MACHINE_AD" ]; then
  RAM_MB=$(awk '/^Memory =/ {print $3}' "$_CONDOR_MACHINE_AD")
  RAM_GB=$(echo "scale=1; $RAM_MB / 1024" | bc)
else
  RAM_GB=$(awk '/MemTotal/ {printf "%.0f", $2/1048576}' /proc/meminfo)
fi
# Allow override; default = nproc
N_PARALLEL=${N_PARALLEL:-$NCPUS}
echo "Slot: ${NCPUS} CPUs, ${RAM_GB} GB RAM   →   xargs -P $N_PARALLEL"

# ----- Discover cells for this plate ---------------------------------------
N_CELLS=$(wc -l < $CELLS_FILE)
echo "Cells to process for plate $PLATENUMBER: $N_CELLS"

MAIN_DIR=$PWD

# ----- Copy raw.root ONCE to local scratch ---------------------------------
LOCAL_RAW=$MAIN_DIR/local_raw
mkdir -p $LOCAL_RAW
EOS_RAW=root://eospublic.cern.ch/$EXP_PRE/RUN$RUN/$RUNSUBDIR/$BRICKFOLDER/$PLATEFOLDER/$BRICKID.$PLATENUMBER.0.0.raw.root
echo "Fetching raw.root once: $EOS_RAW"
T0=$(date +%s)
xrdcp -f $EOS_RAW $LOCAL_RAW/$BRICKID.$PLATENUMBER.0.0.raw.root
T1=$(date +%s)
RAW_GB=$(stat --format='%s' $LOCAL_RAW/$BRICKID.$PLATENUMBER.0.0.raw.root | awk '{printf "%.1f", $1/1073741824}')
echo "raw.root xrdcp: ${RAW_GB} GB in $((T1-T0))s"

# ----- Outputs collected here, xrdcp'd back at end -------------------------
OUTPUT_DIR=$MAIN_DIR/outputs
mkdir -p $OUTPUT_DIR

# ----- Per-cell function ---------------------------------------------------
process_cell() {
  local CELL=$1
  local xcell=$((CELL % 18 + 1))
  local ycell=$((CELL / 18 + 1))
  local CELLFOLDER=cell_${xcell}0_${ycell}0
  local CELL_EXP=$EXP_PRE/RUN$RUN/$RUNSUBDIR/$BRICKFOLDER/cells/$CELLFOLDER/$BRICKFOLDER
  local CELLDIR=$MAIN_DIR/cell_${CELL}
  local WORKDIR=$CELLDIR/$BRICKFOLDER   # viewsideal expects ../b000052/set.root relative to its cwd

  mkdir -p $WORKDIR/$PLATEFOLDER
  cd $WORKDIR

  # Symlink the locally-cached raw.root
  ln -sf $LOCAL_RAW/$BRICKID.$PLATENUMBER.0.0.raw.root $PLATEFOLDER/
  # Cell-specific config from EOS
  ln -sf $CELL_EXP/$BRICKFOLDER.0.0.0.set.root .
  ln -sf $CELL_EXP/viewsideal.rootrc .

  local LOG=$MAIN_DIR/cell_${CELL}.log
  {
    echo "=== cell $CELL (x=$xcell y=$ycell) plate $PLATENUMBER  pid=$$ start=$(date +%s) ==="
    echo "--- env diag ---"
    echo "PWD=$PWD"
    echo "CELL_EXP=$CELL_EXP"
    echo "which viewsideal: $(which viewsideal 2>&1)"
    echo "--- input file check ---"
    ls -lL $PLATEFOLDER/$BRICKID.$PLATENUMBER.0.0.raw.root 2>&1 | head -1
    ls -lL $BRICKFOLDER.0.0.0.set.root                     2>&1 | head -1
    ls -lL viewsideal.rootrc                               2>&1 | head -1
    echo "--- HeaderCut in viewsideal.rootrc ---"
    grep -n HeaderCut viewsideal.rootrc 2>&1
    echo "--- run ---"
    /usr/bin/time -f "viewsideal   wall=%es rss=%MkB"   viewsideal   -id=$BRICKID.$PLATENUMBER.0.0 -v=1
    /usr/bin/time -f "mosalignbeam wall=%es rss=%MkB"   mosalignbeam -id=$BRICKID.$PLATENUMBER.0.0 -v=1
    /usr/bin/time -f "moslink      wall=%es rss=%MkB"   moslink      -id=$BRICKID.$PLATENUMBER.0.0 -v=1
    /usr/bin/time -f "mosmerge     wall=%es rss=%MkB"   moslink      -id=$BRICKID.$PLATENUMBER.0.0 -merge -v=1
    echo "=== cell $CELL done end=$(date +%s) ==="
    echo "--- final dir listing ---"
    ls -la $PLATEFOLDER/
  } > $LOG 2>&1

  # Diagnostic: ship a few cell logs back to EOS so we can actually see failures
  if [ "$CELL" = "0" ] || [ "$CELL" = "162" ] || [ "$CELL" = "323" ]; then
    xrdcp -f $LOG root://eospublic.cern.ch/$EXP_PRE/RUN$RUN/$RUNSUBDIR/$BRICKFOLDER/cell_${CELL}_plate${PLATENUMBER}.log 2>&1 | tail -1
  fi

  # Output flat into shared outputs dir; cell index encoded in filename
  if [ -f $PLATEFOLDER/$BRICKID.$PLATENUMBER.0.0.mos.root ]; then
    mv $PLATEFOLDER/$BRICKID.$PLATENUMBER.0.0.mos.root \
       $OUTPUT_DIR/$BRICKID.$PLATENUMBER.${xcell}.${ycell}.mos.root
  fi
  if [ -f $PLATEFOLDER/$BRICKID.$PLATENUMBER.0.0.cp.root ]; then
    mv $PLATEFOLDER/$BRICKID.$PLATENUMBER.0.0.cp.root \
       $OUTPUT_DIR/$BRICKID.$PLATENUMBER.${xcell}.${ycell}.cp.root
  fi

  cd $MAIN_DIR
  rm -rf $CELLDIR
}
export -f process_cell
export MAIN_DIR PLATENUMBER PLATEFOLDER BRICKID BRICKFOLDER EXP_PRE RUN RUNSUBDIR
export LOCAL_RAW OUTPUT_DIR LD_LIBRARY_PATH LD_PRELOAD XROOTD_VMP EOSSHIP

# ----- Parallel cell loop --------------------------------------------------
echo ""
echo "=== Processing $N_CELLS cells with $N_PARALLEL parallel workers ==="
T0=$(date +%s)
xargs -a $CELLS_FILE -I{} -P $N_PARALLEL bash -c 'process_cell "$@"' _ {}
T1=$(date +%s)
echo "=== All cells done in $((T1-T0))s ==="

# ----- Summary & xrdcp outputs back to EOS ---------------------------------
echo ""
echo "=== Outputs ==="
ls -lh $OUTPUT_DIR/ | head -20
echo "  ... ($(ls $OUTPUT_DIR/ | wc -l) total files)"

echo ""
echo "=== xrdcp outputs back to EOS (parallel, up to $N_PARALLEL workers) ==="
T0=$(date +%s)
upload_cell() {
  local CELL=$1
  local xcell=$((CELL % 18 + 1))
  local ycell=$((CELL / 18 + 1))
  local CELLFOLDER=cell_${xcell}0_${ycell}0
  local DEST_DIR=root://eospublic.cern.ch/$EXP_PRE/RUN$RUN/$RUNSUBDIR/$BRICKFOLDER/cells/$CELLFOLDER/$BRICKFOLDER/$PLATEFOLDER/
  for SUFFIX in mos.root cp.root; do
    local SRC=$OUTPUT_DIR/$BRICKID.$PLATENUMBER.${xcell}.${ycell}.${SUFFIX}
    if [ -f "$SRC" ]; then
      xrdcp -f -N $SRC $DEST_DIR 2>&1 | tail -1
    fi
  done
}
export -f upload_cell
export EXP_PRE RUN RUNSUBDIR BRICKFOLDER PLATEFOLDER BRICKID PLATENUMBER OUTPUT_DIR
xargs -a $CELLS_FILE -I{} -P $N_PARALLEL bash -c 'upload_cell "$@"' _ {}
T1=$(date +%s)
echo "xrdcp upload: $((T1-T0))s"

# ----- Cleanup -------------------------------------------------------------
rm -rf $LOCAL_RAW $O2_LIB_DIR
echo ""
echo "=========================================================================="
echo "Plate $PLATENUMBER complete: $(date)"
echo "=========================================================================="
